### PR TITLE
feat: added data/Bounded

### PR DESCRIPTION
**Pull request by jessekelly881**
Added data/Bounded optics.

### CODE REVIEW

**Comment by jessekelly881** [comment]
@gcanti

**Comment by gcanti** [comment]
@jessekelly881 I don't understand what's use case for this, putting a `Bounded` instance nested in an object looks strange

**Comment by jessekelly881** [comment]
I added it primarily for completeness but I could definitely imagine circumstances where a bounded in an object makes sense. As part of options to a function for example.  In the case of Eq in the previous version on fp-ts a struct of Eqs could be used to create an Eq for the struct. I could imagine something similar being useful in certain circumstances for Bounded. E.g. for constructing a  bound for a point using blunds for the x, y, and z points.

**Comment by jessekelly881** [comment]
@gcanti I added it primarily for completeness but I could definitely imagine circumstances where a bounded in an object makes sense. Given an object like a Point for example you could create a function that creates a bound for the point given bounds for each coordinate(x,y,z...). Similar to constructing an Eq from a struct or a tuple given a struct or tuple of Eq

**Comment by gcanti** [comment]
I don't think it's worth adding code for a use case that is not clearly frequent.

But in any case, isn't it already covered by `at`?

```ts
type S = {
  readonly a: {
    readonly b: Bounded<number>
  }
}

const s: S = { a: { b: N.Bounded } }

describe("Bounded", () => {
  it("min", () => {
    const _b = Optic.id<S>().at("a").at("b").at("minBound")
    expect(Optic.modify(_b)(() => 10)(s)).toEqual({ a: { b: { ...N.Bounded, minBound: 10 } } })
  })
  it("max", () => {
    const _b = Optic.id<S>().at("a").at("b").at("maxBound")
    expect(Optic.modify(_b)(() => 10)(s)).toEqual({ a: { b: { ...N.Bounded, maxBound: 10 } } })
  })
})
```

**Comment by jessekelly881** [comment]
Good point. At clearly works better here. Closing the pr.

**Pull request closed without merging**
